import { meta, shopify, starbucks, tesla } from "../assets/images";
import {
    car,
    contact,
    css,
    estate,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    motion,
    mui,
    nextjs,
    nodejs,
    pricewise,
    react,
    redux,
    sass,
    snapgram,
    summiz,
    tailwindcss,
    threads,
    typescript,
    unity,
    blender,
    mysql,
    cavelabs,
    twitter,
    solarpanel
} from "../assets/icons";

export const skills = [
    {
        imageUrl: html,
        name: "HTML",
        type: "Frontend",
    },
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: express,
        name: "Express",
        type: "Backend",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    {
        imageUrl: mysql,
        name: "MySQL",
        type: "Database",
    },
    {
        imageUrl: nextjs,
        name: "Next.js",
        type: "Frontend",
    },
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Frontend",
    },
    {
        imageUrl: unity,
        name: "Unity",
        type: "3D Modeling and Development Tool",
    },
    {
        imageUrl:blender,
        name: "Blender",
        type: "3D Modeling and Animation Tool",
    },
   
];

export const experiences = [
    {
        title: "Intern in Cave Labs PES University",
        company_name: "Cave Labs",
        icon: cavelabs,
        date: "June 2024 - August 2024",
        points: [
            "Worked as an Intern Under University Professor",
            "Worked on 3D Modeling of the components in Blender and Unity",
            "Worked as Front-End Developer"
            
        ],
    },
    
];

export const socialLinks = [
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/Shashankhosamani',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/shashank-l-h/',
    }
    ,
    {
        name : 'X',
        iconUrl: twitter,
        link:'https://x.com/Shashank__h'
    }
];

export const projects = [
    {
        iconUrl: solarpanel,
        theme: 'btn-back-black',
        name: 'Solar-Panel Array 3D',
        description: 'Developed a web 3D application that Calculates the Power generated by each Solar-Panel at particular Location and time  using Solar Radtion',
        link: 'https://github.com/Shashankhosamani/SolarpanelFabrik',
    },
  
];